### ISSUE TITLE
Idea: add block config to loaders

### ISSUE THREAD

**Issue by mobinni** [andywer/webpack-blocks#12]
So first off I want to say this is an amazing concept. It strips away the complexity of having to setup an entire webpack config.

I had an idea pop into my head and I wanted to run it by you to run it by you.

Currently you are supporting loaders on a case to case basis in your packages folder. My thought was maybe you could add a configuration folder to each loader at the root level. This package folder would signify it supports webpack blocks, for instance a `.block` folder with the index that contains the configuration for that module in a certain form whether it be json, js, etc.

One downside I see is that not all repo's would partake (although I do not see why not). If however they chose not too, you could still support them in a wrapper within this repo.

A major bonus I see here is that block folder would then be updated with the repo of the loader, so it would follow the semantic/configuration changes of that loader. This would mean that the webpack ecosystem as is would remain the same. People install loaders, loaders contain blocks, webpack blocks bootstraps those blocks.

Webpack block would then read the configuration of the block in the main repo, the block would be more of generic builder function.

```
import {createConfig, compose} from 'webpack-blocks';
const wpDevServer = require('webpack-dev-server/block');
 // creates a builder function based off the config
const blocks = compose(wpDevServer(/*config*/), ...);

export createConfig(...blocks);

```

I am of course open to feedback and possible drawbacks.

Sincerely,
Mo Binni

**Comment by andywer** [comment]
Hey @mobinni. Thanks for sharing your idea and the kind words!

Putting the webpack block into the loader package seems like an interesting thought. Of course it would require the package owners of the loaders to be cool with it, what might be an issue.

But the main problem I see is that the API of webpack-blocks might change over time. If there is a breaking change / a major release of webpack-blocks which requires the blocks to be updated in order to work with the new version it would then also require an update of the loader package.

So even if the loader is well maintained you would need to *use the new loader version in order to use the new webpack-blocks version* and vice versa *you cannot use an older loader version with the new webpack-blocks version* then.

That looks like a deal-breaker...

**Comment by andywer** [comment]
(Changed from *feature req* to *idea*, since it's rather a feature req for the loaders than webpack-blocks)

**Comment by mobinni** [comment]
I completely understand that point of view, however my stance is that even breaking changes should support some type of backwards compatibility. My feeling is that OSS has the nature to push the boundaries of software development. 

However, we've also reached the point were enterprises, and other places start to use our software. I can say from experience that backwards compatibility has become extremely important.

I'm not saying it's something that you should be doing now, splitting out all the blocks and trying to distribute them, however you could take the architectural points into consideration and build your loaders in such a way that when the API becomes stable you could pose the question to release blocks as a support system inside loaders.

Just a thought tho, also thanks for changing the tags, it was more a question/brainstorm than an actual feature.

**Comment by andywer** [comment]
For the breaking changes I would rely on semantic versioning (breaking change means major version bump, so `npm`/`yarn` won't update it automatically). That's what safes us all every day :)

Thinking about making it part of the block contribution process, though: https://github.com/andywer/webpack-blocks/issues/14#issuecomment-265379880

I hope it's fine if I close it for now. Feel free to re-open if not ;)
