### ISSUE TITLE
Merging webpack-parts into webpack-blocks

### ISSUE THREAD

**Issue by aaronjensen** [andywer/webpack-blocks#122]
Howdy, last week I created webpack-parts before I knew that webpack-blocks was a thing. I'm quite happy to use webpack-blocks as a basis for our config and get rid of webpack-parts entirely.

We're going to start that migration today and I wanted to check with you to see which parts/blocks you'd think would be a good fit for the main repo.

Here are the ones we have that blocks doesn't yet have:

https://substantial.github.io/webpack-parts/#outputvendornodemodules
https://substantial.github.io/webpack-parts/#loadimages
https://substantial.github.io/webpack-parts/#devanalyze
https://substantial.github.io/webpack-parts/#optimizeforcesinglelodash
https://substantial.github.io/webpack-parts/#optimizeremovemomentlocales
https://substantial.github.io/webpack-parts/#uiprogressbar
https://substantial.github.io/webpack-parts/#devhotmodulereloading
https://substantial.github.io/webpack-parts/#setupcopyenv

We're happy to keep any/all of them in our own repos, but would love to contribute back as many as you'd like. Thanks!

**Comment by andywer** [comment]
Hey @aaronjensen! Thanks for sharing :)

I quickly browsed through them, but will have another deeper looker into it. I hope the `module.loaders` vs `module.rules` won't hurt for now. But there is a clean transition to `module.rules` in sight: #111

**Comment by sapegin** [comment]
I think we should reevaluate this again — I see some useful parts and would like to have them in blocks. And some we already have.

**Comment by andywer** [comment]
Yes, very much so! Just no time to do it right now... Sorry.

**Comment by sapegin** [comment]
You don’t have to do everything, just make an issue and tweet it ;-)

**Comment by sapegin** [comment]
> https://substantial.github.io/webpack-parts/#outputvendornodemodules

In progress: #188.

https://substantial.github.io/webpack-parts/#loadimages

`assets` block has something similar.

https://substantial.github.io/webpack-parts/#optimizeforcesinglelodash

I’d like to have something similar but to use `import { map } from 'lodash'` and  probably it’s outside of the core.

https://substantial.github.io/webpack-parts/#devhotmodulereloading

I think we have it in the core but thinking about moving this to a third-party plugin.

https://substantial.github.io/webpack-parts/#setupcopyenv

I want `setEnv` as more generic and useful block, but we need to convince @andywer that it’s useful ;-)

@aaronjensen I’m going to close this issue since webpack-parts is already [deprecated](https://github.com/substantial/webpack-parts#deprecation-notice) (thanks for suggesting webpack-blocks!). Feel free to open issues for things that are still missed from webpack-blocks.

**Comment by aaronjensen** [comment]
Sounds good, thanks.
