### ISSUE TITLE
Generating stats.json

### ISSUE THREAD

**Issue by eXon** [andywer/webpack-blocks#18]
It would be great to add an option to generate the stats.json file out of the box.

I use this on most of my project. Maybe this would be easy to plug.

This is an example of a plugin I use to do it:

```js
const chunks = ['assetsByChunkName', 'publicPath'];

function generateWebpackStats() {
  this.plugin('done', stats => {
    const webpackStats = stats.toJson({ chunks: true });

    // Only keep what we need for the server
    for (var key in webpackStats) {
      if (chunks.indexOf(key) < 0) {
        delete webpackStats[key];
      }
    }

    fs.writeFileSync(file, JSON.stringify(webpackStats, null, 4));
  });
}
```

**Comment by andywer** [comment]
Hey @eXon. Thanks for sharing!

-Sounds like a potential additional feature for the core `webpack` block.- (Nope. Since it introduces a new package dependency, so it should go into a separate block)

How about using [webpack-stats-plugin](https://github.com/FormidableLabs/webpack-stats-plugin) to achieve that?

Creating a webpack block for that should be a piece of cake :)

**Comment by eXon** [comment]
I guess I'm old school, I wrote mine before this plugin was even existing xD. But yea, I think you're right about that. I'll try some stuff.

**Comment by eXon** [comment]
After using webpack-stats-plugin, it certainly doesn't deserve a block just to do this xD:

```js
addPlugins([
    new StatsWriterPlugin(),
])
```
