### ISSUE TITLE
extract-text2 fails to work out of the box.

### ISSUE THREAD

**Issue by PolyPik** [andywer/webpack-blocks#181]
I've decided to tweak the [Atomic React boilerplate](https://github.com/diegohaz/arc) so it could use [react-fa](https://github.com/andreypopp/react-fa).

While there is no problem with merely including the icons via style tags, I've encountered issues with using the extract-text2 block to extract the third-party font-awesome stylesheet.

I've managed to workaround this issue by using a custom block, but I would prefer it if someone here could help me get the extract-text2 block working as intended.

EDIT: Sorry, that I didn't describe the symptoms the first time.

What happens is that webpack complains about the font-awesome.css file and states that it is missing an appropriate loader. but my _node_modules_ directory contains **css-loader** and **style-loader**. So what's causing the issue here?

**Comment by andywer** [comment]
Hi @PolyPik.
It's unfortunate that it doesn't work as expected, but it is quite likely that your issue vanishes when using the 1.0 beta. A lot has changed there concerning css loading and we will release the 1.0 release candidate very soon.

Since you said you have a work-around, may I propose an alternative approach?

Let's create an issue for the [atomic react boilerplate](https://github.com/diegohaz/arc) to make it use webpack-blocks 1.0 beta, since the 0.x will be deprecated soon anyway.
@diegohaz If you need any help on migrating to 1.0, feel free to shout and I will try to help 😉

**Comment by vlad-zhukov** [comment]
This looks outdated and was most likely fixed.

**Comment by andywer** [comment]
(👍 The issue smells like the deprecated v0.4 😉)
