### ISSUE TITLE
postcss webpack block

### ISSUE THREAD

**Issue by alextrastero** [andywer/webpack-blocks#23]
Hiya,
I'm wondering here, the sass webpack block `index.js` defines the following:
`loaders: [ 'style-loader', 'css-loader', 'sass-loader' ]`
And the postcss webpack block is so:
`loaders: [ 'postcss-loader' ]`
But the postcss-loader specifies that you need `style-loader` and `css-loader`.
So my question is, how can I add a separate loader without using the "blocks" approach to make this work?

Only using the post-css webpack block I get the following error:
```js
var content = require("!!./../node_modules/css-loader/index.js!./App.css");
ERROR > if(typeof content === 'string') content = [[module.id, content, '']];
```
Which I think is because I don't have the style nor css loader installed.

Thanks in advance!

**Comment by alextrastero** [comment]
My `webpack.config.js`
```JS
const { addPlugins, createConfig, entryPoint, env, setOutput, sourceMaps, webpack } = require('@webpack-blocks/webpack')
const babel = require('@webpack-blocks/babel6')
const postcss = require('@webpack-blocks/postcss')
const devServer = require('@webpack-blocks/dev-server')
const cssnext = require("postcss-cssnext")

const path = require('path')
const autoprefixer = require('autoprefixer')

module.exports = createConfig([
  entryPoint('./src'),
  setOutput({
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/dist/'
  }),
  addPlugins([
    new webpack.DefinePlugin({
      'process.env': JSON.stringify(process.env || 'development')
    })
  ]),
  babel(),
  postcss([
    cssnext(),
    autoprefixer({ browsers: ['last 2 versions'] })
  ]),
  env('development', [
    devServer(),
    sourceMaps(),
    devServer.reactHot(),
  ]),
])
```

**Comment by andywer** [comment]
Hi @alextrastero.

The `loaders: [ 'style-loader', 'css-loader', 'sass-loader' ]` vs. `loaders: [ 'postcss-loader' ]` seems a little odd, but makes sense, because
* the postcss block is extending the `.css` loaders (which by default already got the `style-loader` and `css-loader`)
* while the sass block needs to set `style-loader` and `css-loader`, because there are no defaults set for `.scss|.sass`

I am stuck, though, concerning the rest of your question. Do you want to use `postcss` on the `sass` files and it does not work?

**Comment by alextrastero** [comment]
@andywer thanks for the quick reply, I want to use the postcss, but was checking the source to see if something was missing and comparing to the sass one :)

**Comment by alextrastero** [comment]
And the error is:
`
ERROR in ./src/App.css
Module build failed: Unknown word (5:1)
`

**Comment by andywer** [comment]
@alextrastero I set up a tiny sample project and tried your config and it seems to work. But I also have some questions left.

The most important one: Where does this line you mentioned come from? (Looks like the style-loader is missing in the require())
```js
var content = require("!!./../node_modules/css-loader/index.js!./App.css");
```

**Comment by andywer** [comment]
I just stumbled upon something similar while writing end-to-end tests for the webpack2 block. Guess the missing `style-loader` and `css-loader` did cause a problem though, since the `postcss-loader` seemed to get prepended instead of appended.

Merged #28 and published `@webpack-blocks/postcss v0.2.0`. Please try that fixed version and tell me if it fixes your issue :)

**Comment by alextrastero** [comment]
massive! thanks, will test asap

**Comment by alextrastero** [comment]
Works like a charm 🙇
