### ISSUE TITLE
Support for babel-preset-env

### ISSUE THREAD

**Issue by amilajack** [andywer/webpack-blocks#37]
https://github.com/babel/babel-preset-env is a huge leap in babel's progress towards simplification. Maybe it should be used by default instead of `babel6`.

Thoughts?

**Comment by andywer** [comment]
Hey @amilajack. I agree that babel-preset-env is pretty damn cool.

But: What do you mean by "Maybe it should be used by default instead of babel6"?
You need the `babel6` block to set up the babel loader. You configure the babel presets/plugins you want to use in your `package.json` or `.babelrc`.

If you want to use `babel-preset-env` just add it to your babel config :) The `babel6` block doesn't care what babel config you set 😉

**Comment by andywer** [comment]
Does that answer your question?

Maybe the documentation needs to be improved. Feel free to suggest documentation changes to make that clearer in the future :)

**Comment by amilajack** [comment]
Ahh i see. I was thinking about a pre-configured babel configuration. But I think using a `.babelrc` and being able to customize it should suffice. Thanks for clarifying!

**Comment by andywer** [comment]
No problem, but you still have a point. If you combine the features #24 and #8 you got webpack presets shipping with a default babel config :)
