### ISSUE TITLE
Desktop application to configure webpack-blocks

### ISSUE THREAD

**Issue by eXon** [andywer/webpack-blocks#73]
While writing a configuration with code is by far the most flexible way of doing it, it would be great to be able to use a desktop application to make things more easy and clear to use.

We talked before about a CLI tool, but I think the UI would be too complex just for the console.

With webpack-blocks, the concept of blocks is very present and it would be cool to make that more visual. You could configure each block, drag&drop them in the order you want them, group or split them when using `env` and `group` blocks and load/save your webpack.config.js file.

I think it should let people do what they want within the code and at the same time give an easy way to edit it within the application.

I know this is not a simple challenge but I would like to explore it from a user perspective first.

To build the application, we could use [Electron](http://electron.atom.io/) so that it is cross-platform and powered by the beautiful Web behind :)

I'll try to draw a mockup this week to expose more the idea and from there let me know what you think!

I'll start something in a different repo as a starting point but I feel like Andy and the other contributors might have great ideas about that too.

**Comment by andywer** [comment]
Hey @eXon. Sounds to me like #4 (you might have not seen it before, since it's closed).

Some questions / thoughts:

1. Why a desktop application that you have to install first instead of a web app?
2. I like that you think about new ways to go :)
3. But: I am not sure if many users will like to use a UI-heavy app for configuring webpack. I think it is either very simple to set up the config (then the CLI tool will do) or you want to create a complex and highly-customized solution (then writing it as a JS file as of now will probably be much faster).
4. Most people will probably just want to set up the webpack config once and then never care about it again. Not sure if installing an app is already an overkill.
5. If an app, then electron, sure :)

For future reference: The (not yet existing) CLI tool that was mentioned is described in #7.

**Comment by eXon** [comment]
@andywer Sometimes I forget how easy it is to use webpack-blocks compared to regular wepback config files. I'll keep thinking about it.

Maybe an effort to improve the documentation would be a better investment of my time.

**Comment by andywer** [comment]
@eXon I didn't want to talk it out of you just like that, I just had some concerns 😉

Better documentation would be quite helpful I think. As soon as we resolve #60 a medium post about how to set up a webpack config using webpack-blocks and that preset in 3 minutes would be a really cool thing, too 😊

**Comment by andywer** [comment]
Anything new here? Otherwise I would close the issue for now 😉
